site_name: My Docs
site_url: https://matthew-sochor.github.io/
site_author: Matthew Sochor

repo_name: matthew-sochor/matthew-sochor.github.io
repo_url: https://github.com/matthew-sochor/matthew-sochor.github.io
theme:
  name: material

nav:
- Home: index.md